web server install cleanup, cgi, web, and executables in different locations

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -429,7 +429,7 @@ PACKAGE_VERSION='2.1.6'
 PACKAGE_STRING='puff 2.1.6'
 PACKAGE_BUGREPORT='rorik@gi.alaska.edu'
 
-ac_default_prefix=`pwd`
+ac_default_prefix=`(cd ..; pwd)`
 # Factoring default headers for most tests.
 ac_includes_default="\
 #include <stdio.h>
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT NETCDF_LIB NETCDF_INC PUFF_NEED_LIBDMAPF_TRUE PUFF_NEED_LIBDMAPF_FALSE ASHXP_BUILD_LIBJPEG_TRUE ASHXP_BUILD_LIBJPEG_FALSE WGET PERL WGRIB CONVERT GMTSET PSCOAST PSBASEMAP PSXY PSTEXT PSCONTOUR MAKECPT GIFSICLE CGIHOME ASHDUMP PATH_TO_WEBPUFF INSTALL_DIR PUFF_NEED_GETOPT_LONG_TRUE PUFF_NEED_GETOPT_LONG_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT NETCDF_LIB NETCDF_INC PUFF_NEED_LIBDMAPF_TRUE PUFF_NEED_LIBDMAPF_FALSE ASHXP_BUILD_LIBJPEG_TRUE ASHXP_BUILD_LIBJPEG_FALSE WGET PERL WGRIB CONVERT GMTSET PSCOAST PSBASEMAP PSXY PSTEXT PSCONTOUR MAKECPT GIFSICLE NCKS GHOSTSCRIPT CGIHOME ASHDUMP PATH_TO_WEBPUFF INSTALL_DIR PUFF_NEED_GETOPT_LONG_TRUE PUFF_NEED_GETOPT_LONG_FALSE BUILD_INSTALL_DOCS_TRUE BUILD_INSTALL_DOCS_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1085,6 +1085,7 @@ Optional Packages:
                           include additional configurations [automatic]
   --with-freetype         use freetype fonts (default is no)
   --with-statistics       add statistical information(default is no)
+  --with-documentation    make/install docs(default is yes)
 
 Some influential environment variables:
   CC          C compiler command
@@ -2098,6 +2099,7 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
 # make the default install directory this one
+#AC_PREFIX_DEFAULT(`pwd`)
 
 
 ac_ext=c
@@ -4302,7 +4304,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4305 "configure"' > conftest.$ac_ext
+  echo '#line 4307 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5410,7 +5412,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5413:" \
+echo "$as_me:5415:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6444,11 +6446,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6449: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6451: \$? = $ac_status" >&5
+   echo "$as_me:6453: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6677,11 +6679,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6680: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6682: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6684: \$? = $ac_status" >&5
+   echo "$as_me:6686: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6737,11 +6739,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6740: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6742: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6744: \$? = $ac_status" >&5
+   echo "$as_me:6746: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8071,7 +8073,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8074 "configure"' > conftest.$ac_ext
+    echo '#line 8076 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8942,7 +8944,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8945 "configure"
+#line 8947 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9040,7 +9042,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9043 "configure"
+#line 9045 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11219,11 +11221,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11222: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11224: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11226: \$? = $ac_status" >&5
+   echo "$as_me:11228: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11279,11 +11281,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11282: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11284: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11286: \$? = $ac_status" >&5
+   echo "$as_me:11288: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11790,7 +11792,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11793 "configure"' > conftest.$ac_ext
+    echo '#line 11795 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12661,7 +12663,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12664 "configure"
+#line 12666 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12759,7 +12761,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12762 "configure"
+#line 12764 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13586,11 +13588,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13589: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13591: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13593: \$? = $ac_status" >&5
+   echo "$as_me:13595: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13646,11 +13648,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13649: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13651: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13653: \$? = $ac_status" >&5
+   echo "$as_me:13655: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14960,7 +14962,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14963 "configure"' > conftest.$ac_ext
+    echo '#line 14965 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15701,11 +15703,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15704: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15706: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15708: \$? = $ac_status" >&5
+   echo "$as_me:15710: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15934,11 +15936,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15937: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15939: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15941: \$? = $ac_status" >&5
+   echo "$as_me:15943: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15994,11 +15996,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15999: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16001: \$? = $ac_status" >&5
+   echo "$as_me:16003: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17328,7 +17330,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17331 "configure"' > conftest.$ac_ext
+    echo '#line 17333 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18199,7 +18201,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18202 "configure"
+#line 18204 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18297,7 +18299,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18300 "configure"
+#line 18302 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22313,6 +22315,87 @@ fi
 
 
 
+# Extract the first word of "ncks", so it can be a program name with args.
+set dummy ncks; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_NCKS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $NCKS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_NCKS="$NCKS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_NCKS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+NCKS=$ac_cv_path_NCKS
+
+if test -n "$NCKS"; then
+  echo "$as_me:$LINENO: result: $NCKS" >&5
+echo "${ECHO_T}$NCKS" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+#AC_ARG_VAR(NCKS, path to ncks)
+
+# Extract the first word of "gs", so it can be a program name with args.
+set dummy gs; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GHOSTSCRIPT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GHOSTSCRIPT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GHOSTSCRIPT="$GHOSTSCRIPT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_GHOSTSCRIPT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+GHOSTSCRIPT=$ac_cv_path_GHOSTSCRIPT
+
+if test -n "$GHOSTSCRIPT"; then
+  echo "$as_me:$LINENO: result: $GHOSTSCRIPT" >&5
+echo "${ECHO_T}$GHOSTSCRIPT" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 
 
 if test "$prefix" != "NONE"; then
@@ -22688,6 +22771,27 @@ _ACEOF
 
 fi
 #############################################
+# give the option not to build documentation
+
+# Check whether --with-documentation or --without-documentation was given.
+if test "${with_documentation+set}" = set; then
+  withval="$with_documentation"
+  with_documentation=$withval
+else
+  with_documentation=yes
+fi;
+
+
+
+if test "$with_documentation" == "yes"; then
+  BUILD_INSTALL_DOCS_TRUE=
+  BUILD_INSTALL_DOCS_FALSE='#'
+else
+  BUILD_INSTALL_DOCS_TRUE='#'
+  BUILD_INSTALL_DOCS_FALSE=
+fi
+
+#############################################
 case $build in
   powerpc-apple-darwin6.8)
 cat >>confdefs.h <<\_ACEOF
@@ -22707,7 +22811,9 @@ esac
 
                                         ac_config_files="$ac_config_files Makefile src/Makefile src/libsrc/Makefile test/Makefile"
 
-                              ac_config_files="$ac_config_files doc/Makefile src/perl/Makefile web/Makefile"
+                    ac_config_files="$ac_config_files src/perl/Makefile web/Makefile"
+
+          ac_config_files="$ac_config_files doc/Makefile"
 
           ac_config_files="$ac_config_files web/mini_httpd/Makefile"
 
@@ -22877,6 +22983,13 @@ if test -z "${PUFF_NEED_GETOPT_LONG_TRUE}" && test -z "${PUFF_NEED_GETOPT_LONG_F
   { { echo "$as_me:$LINENO: error: conditional \"PUFF_NEED_GETOPT_LONG\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"PUFF_NEED_GETOPT_LONG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_INSTALL_DOCS_TRUE}" && test -z "${BUILD_INSTALL_DOCS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_INSTALL_DOCS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_INSTALL_DOCS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23332,9 +23445,9 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/libsrc/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/libsrc/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
-  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "src/perl/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/perl/Makefile" ;;
   "web/Makefile" ) CONFIG_FILES="$CONFIG_FILES web/Makefile" ;;
+  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "web/mini_httpd/Makefile" ) CONFIG_FILES="$CONFIG_FILES web/mini_httpd/Makefile" ;;
   "src/libsrc/dmapf-c/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/libsrc/dmapf-c/Makefile" ;;
   "src/ashxp/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ashxp/Makefile" ;;
@@ -23524,12 +23637,16 @@ s,@PSTEXT@,$PSTEXT,;t t
 s,@PSCONTOUR@,$PSCONTOUR,;t t
 s,@MAKECPT@,$MAKECPT,;t t
 s,@GIFSICLE@,$GIFSICLE,;t t
+s,@NCKS@,$NCKS,;t t
+s,@GHOSTSCRIPT@,$GHOSTSCRIPT,;t t
 s,@CGIHOME@,$CGIHOME,;t t
 s,@ASHDUMP@,$ASHDUMP,;t t
 s,@PATH_TO_WEBPUFF@,$PATH_TO_WEBPUFF,;t t
 s,@INSTALL_DIR@,$INSTALL_DIR,;t t
 s,@PUFF_NEED_GETOPT_LONG_TRUE@,$PUFF_NEED_GETOPT_LONG_TRUE,;t t
 s,@PUFF_NEED_GETOPT_LONG_FALSE@,$PUFF_NEED_GETOPT_LONG_FALSE,;t t
+s,@BUILD_INSTALL_DOCS_TRUE@,$BUILD_INSTALL_DOCS_TRUE,;t t
+s,@BUILD_INSTALL_DOCS_FALSE@,$BUILD_INSTALL_DOCS_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
